name: Release and Push Docker Image

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

jobs:
  create-release-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Generate release tag
        id: tag
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ "$latest_tag" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            patch=$((patch + 1))
            new_tag="v$major.$minor.$patch"
          else
            new_tag="v1.0.0"
          fi
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
          git tag $new_tag
          git push origin $new_tag

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            your-dockerhub-username/your-image-name:latest
            your-dockerhub-username/your-image-name:${{ steps.tag.outputs.new_tag }}
